name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: divmora/.github/.github/workflows/go-ci.yml@main

  cfn-ci:
    uses: divmora/.github/.github/workflows/cfn-ci.yml@main
    with:
      template-directory: 'deploy/cloudformation'
